// flow-typed signature: b5032ff5205bfe2d6ad1daad270849ed
// flow-typed version: <<STUB>>/css-loader_v^0.14.5/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-loader/lib/css-base' {
  declare module.exports: any;
}

declare module 'css-loader/lib/generateLocals' {
  declare module.exports: any;
}

declare module 'css-loader/lib/getLocalIdent' {
  declare module.exports: any;
}

declare module 'css-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'css-loader/lib/localsLoader' {
  declare module.exports: any;
}

declare module 'css-loader/lib/parseSource' {
  declare module.exports: any;
}

declare module 'css-loader/lib/processLocals' {
  declare module.exports: any;
}

declare module 'css-loader/lib/ReplaceMany' {
  declare module.exports: any;
}

declare module 'css-loader/locals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-loader/index' {
  declare module.exports: $Exports<'css-loader'>;
}
declare module 'css-loader/index.js' {
  declare module.exports: $Exports<'css-loader'>;
}
declare module 'css-loader/lib/css-base.js' {
  declare module.exports: $Exports<'css-loader/lib/css-base'>;
}
declare module 'css-loader/lib/generateLocals.js' {
  declare module.exports: $Exports<'css-loader/lib/generateLocals'>;
}
declare module 'css-loader/lib/getLocalIdent.js' {
  declare module.exports: $Exports<'css-loader/lib/getLocalIdent'>;
}
declare module 'css-loader/lib/loader.js' {
  declare module.exports: $Exports<'css-loader/lib/loader'>;
}
declare module 'css-loader/lib/localsLoader.js' {
  declare module.exports: $Exports<'css-loader/lib/localsLoader'>;
}
declare module 'css-loader/lib/parseSource.js' {
  declare module.exports: $Exports<'css-loader/lib/parseSource'>;
}
declare module 'css-loader/lib/processLocals.js' {
  declare module.exports: $Exports<'css-loader/lib/processLocals'>;
}
declare module 'css-loader/lib/ReplaceMany.js' {
  declare module.exports: $Exports<'css-loader/lib/ReplaceMany'>;
}
declare module 'css-loader/locals.js' {
  declare module.exports: $Exports<'css-loader/locals'>;
}
