// flow-typed signature: 5bbeeba6fa4f0f7234a89f82b985aadb
// flow-typed version: <<STUB>>/gulp-merge-json_v^0.4.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-merge-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-merge-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-merge-json/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-merge-json/index' {
  declare module.exports: $Exports<'gulp-merge-json'>;
}
declare module 'gulp-merge-json/index.js' {
  declare module.exports: $Exports<'gulp-merge-json'>;
}
declare module 'gulp-merge-json/test/main.js' {
  declare module.exports: $Exports<'gulp-merge-json/test/main'>;
}
