// flow-typed signature: 3bf75d3ad200d5161b3d25e815cb1ad1
// flow-typed version: <<STUB>>/gulp-size_v^1.2.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-size/index' {
  declare module.exports: $Exports<'gulp-size'>;
}
declare module 'gulp-size/index.js' {
  declare module.exports: $Exports<'gulp-size'>;
}
