// flow-typed signature: db0304a703ca208627597c9fffd388a0
// flow-typed version: <<STUB>>/html-webpack-plugin_v^1.5.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-plugin/index' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
