// flow-typed signature: 2c9d4f20431b60fa5e323e9d11ab99ae
// flow-typed version: <<STUB>>/react-transform-hmr_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transform-hmr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transform-hmr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transform-hmr/lib/index' {
  declare module.exports: any;
}

declare module 'react-transform-hmr/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transform-hmr/lib/index.js' {
  declare module.exports: $Exports<'react-transform-hmr/lib/index'>;
}
declare module 'react-transform-hmr/src/index.js' {
  declare module.exports: $Exports<'react-transform-hmr/src/index'>;
}
